<?php
/**
 * @file
 * RSVP Module Hooks
 */

use Drupal\Core\Form\FormStateInterface;


/**
 * Implements hook_form_alter()
 *
 * Alter the node add/edit form to include admin settings for displaying RSVPBlock
 *
 * @param $form
 * @param  \Drupal\Core\Form\FormStateInterface  $form_state
 * @param $form_id
 */
function rsvplist_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
  $node = $form_state->getFormObject()->getEntity();
  $current_node_type = $node->getType();
  $config = \Drupal::config('rsvplist.settings');
  $types = $config->get('allowed_types');

  //RSVP Options for administrator
  if (in_array($current_node_type, $types)){
    $form['rsvplist'] = array(
      '#type' => 'details',
      '#title' => t('RSVP Collection'),
      '#access' => \Drupal::currentUser()->hasPermission('administer rsvplist'),
      '#group' => 'advanced',
      '#weight' => 100
    );

    /** @var \Drupal\rsvplist\EnablerService $enabler */
    $enabler = Drupal::service('rsvplist.enabler');

    $form['rsvplist']['rsvplist_enabled'] = array(
      '#type' => 'checkbox',
      '#title' => t('Collect RSVP e-mails for this node'),
      '#default_value' => $enabler->isEnabled($node)
    );

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type'])
        && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'rsvplist_form_node_form_submit';
      }
    }
  }
}

/**
 * Form submission handler for RSVP item field on the node form
 *
 * @param  array  $form
 * @param  \Drupal\Core\Form\FormStateInterface  $formState
 *
 * @see \rsvplist_form_node_form_alter()
 *
 */
function rsvplist_form_node_form_submit(array $form, FormStateInterface $formState) {
  /** @var Drupal\rsvplist\EnablerService $enabler */
  $enabler = Drupal::service('rsvplist.enabler');
  $node = $formState->getFormObject()->getEntity();
  if($enabled = $formState->getValue('rsvplist_enabled')) {
    $enabler->setEnabled($node);
  }
  else {
    $enabler->delEnabled($node);
  }
}
